[package]
name = "hello_world"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
edition = "2018"
default-run = "hello_world"

[dependencies]
itertools = "0.8.0"
istring = { path="../istring/"}
byteorder = "1.3.2"
rayon = "1.1.0"

[profile.release]
debug = true
